version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
