import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en">
      <UserProvider>
=======
      <html lang="en">
>>>>>>> 449cd71cf7834e6b3e64c2d7fc18a53c637a8a8d
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
<<<<<<< HEAD
      </UserProvider>
    </html>
=======
      </html>
>>>>>>> 449cd71cf7834e6b3e64c2d7fc18a53c637a8a8d
  );
}
